### ISSUE TITLE
Sometimes queue buggs

### ISSUE THREAD

**Issue by PollieDev** [ThePjpollie/MusicMaistro#7]
Sometimes (most of the times when adding a playlist) the queue buggs. 
It shows all information correctly except the *Requested by* part, it looks like:

Requested byRequested by **Pollie#8264Pollie#8264**
![discord_2018-01-21_12-53-46](https://user-images.githubusercontent.com/12276548/35193879-20b7c552-feaa-11e7-9a42-53125edc8fee.png)

**Comment by nitrog0d** [comment]
Are you sure it's your Bot? sometimes Discord does it, try restarting it? 🤔

**Comment by PollieDev** [comment]
I am not sure yet. It already happened a couple of times. So a restart won't fix it.
The weird thing is I add to the message `"Requested by ${message.author.id}"`.

If it was the code running twice then the line should look like:
Requested by **Pollie#8264**Requested by **Pollie#8264**

Then I would be ok and know it's the code running twice. But that's not the case so it could be Discord. Not sure

**Comment by nitrog0d** [comment]
I mean, rejoin in the channel or restart Discord

**Comment by PollieDev** [comment]
Ooh, like that. Good question, haven't tried! Will check soon

**Comment by nitrog0d** [comment]
I forgot to say, it happens when you edit a big message, sorry

**Comment by PollieDev** [comment]
After testing it once again you are correct!
It was bugged, restarted Discord and was gone. So this is something local what is what I assume hard to prevent :I

Thanks for the idea though :)
